language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./scripts/build.sh

after_success:
  - for f in $(find build -name '*.gcno'); do gcov-6 $f; done
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

env:
  global:
    - LANG="en_US.UTF-8"
