language: cpp
sudo: false
dist: trusty
compiler:
  - clang++

matrix:
  include:
    os:
      - linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
          - lcov
    env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

branches:
  only:
    - master

before_install:
  - eval "${MATRIX_EVAL}"

script: ./scripts/build.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make UnitTestCoverage
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

env:
  global:
    - LANG="en_US.UTF-8"
