language: cpp
sudo: false
dist: trusty
compiler:
  - g++
os:
  - linux
lang: cpp
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
branches:
  only:
  - master
before_script:
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz
  - tar -xvzf cmake-3.9.1-Linux-x86_64.tar.gz
  - export PATH=$PATH:$PWD/cmake-3.9.1-Linux-x86_64/bin
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
env:
  global:
    - LANG="en_US.UTF-8"
